name: CI
on:
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
            fetch-depth: 0
      
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15.10.0

      - name: Install dependencies
        run: yarn

      - name: Test
        run: yarn test --coverage

      - name: Check linting
        run: yarn lint

      - name: Check commit message
        uses: wagoid/commitlint-github-action@v1